package com.the3Cgrp.zupptrade.shared.enums;

public enum TradeStatus {
    PENDING_CONFIRM, // generated by Agent 2, awaiting user confirm — expires in 20 min
    CONFIRMED,       // user confirmed, forwarded to Agent 5
    REJECTED,        // user rejected
    ACTIVE,          // Agent 5 filled both legs, Agent 3 monitoring
    CLOSED           // exited by Agent 3 or expiry
}
