package com.the3Cgrp.zupptrade.shared.enums;

public enum TradeStatus {
    PENDING_CONFIRM,    // generated by Agent 2, awaiting user confirm — expires in 20 min
    CONFIRMED,          // user confirmed, forwarded to Agent 5
    REJECTED,           // user rejected
    ACTIVE,             // Agent 5 filled both legs, Agent 3 monitoring
    EXIT_IN_PROGRESS,   // Agent 3 triggered EXIT; Agent 5 exit order placed but not yet confirmed
    EXIT_FAILED,        // Agent 5 exit failed — position still open; Agent 3 will retry next cycle
    CLOSED              // exited by Agent 3/5, expired, or externally closed on Upstox
}
