package com.the3Cgrp.zupptrade.agent2.service;

import tools.jackson.core.type.TypeReference;
import com.the3Cgrp.zupptrade.agent2.client.MarketDataClient;
import com.the3Cgrp.zupptrade.agent2.client.OptionChainClient;
import com.the3Cgrp.zupptrade.agent2.domain.entity.TradeEntity;
import com.the3Cgrp.zupptrade.agent2.engine.RecommendationEngine;
import com.the3Cgrp.zupptrade.agent2.repository.Agent1SignalRepository;
import com.the3Cgrp.zupptrade.agent2.repository.ReferenceDataRepository;
import com.the3Cgrp.zupptrade.agent2.repository.TradeRepository;
import com.the3Cgrp.zupptrade.agent2.repository.UserProfileRepository;
import com.the3Cgrp.zupptrade.agent2.util.JsonUtil;
import com.the3Cgrp.zupptrade.ledger.TradeLedgerService;
import com.the3Cgrp.zupptrade.shared.dto.MonitorThresholdsDto;
import com.the3Cgrp.zupptrade.shared.dto.TradeLegDto;
import com.the3Cgrp.zupptrade.shared.dto.TradeConfirmRequestDto;
import com.the3Cgrp.zupptrade.agent2.domain.model.TradeSummary;
import com.the3Cgrp.zupptrade.shared.enums.ConfirmAction;
import com.the3Cgrp.zupptrade.shared.enums.LegAction;
import com.the3Cgrp.zupptrade.shared.enums.OptionType;
import com.the3Cgrp.zupptrade.shared.enums.Strategy;
import com.the3Cgrp.zupptrade.shared.enums.TradeStatus;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

/**
 * Unit tests for RecommendationService.applyThresholdOverride(), exercised via confirm().
 *
 * Covers:
 *  - Null override → no-op
 *  - Valid PE short override (all 3 fields, partial fields)
 *  - Valid CE short override
 *  - T3 below PE short strike → IllegalArgumentException (PoP < 50%)
 *  - T3 above CE short strike → IllegalArgumentException (PoP < 50%)
 *  - Ordering violations (T1/T2/T3 not descending for PE / ascending for CE) → IllegalArgumentException
 *  - Iron Condor override → silently ignored
 *
 * All Spring/JPA/Upstox dependencies are mocked. JsonUtil is mocked to avoid
 * ObjectMapper configuration complexity in a pure unit test.
 *
 * Trade entity is constructed directly with new TradeEntity() + setters.
 * The entity id remains null (generated by JPA only) — acceptable here because
 * it is only used in log statements and the mocked ledger.record() call.
 */
@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
class ConfirmThresholdOverrideTest {

    @Mock private TradeRepository          tradeRepository;
    @Mock private JsonUtil                 jsonUtil;
    @Mock private TradeLedgerService       ledger;
    @Mock private Agent1SignalRepository   signalRepository;
    @Mock private UserProfileRepository    userProfileRepository;
    @Mock private ReferenceDataRepository  referenceDataRepository;
    @Mock private OptionChainClient        optionChainClient;
    @Mock private MarketDataClient         marketDataClient;
    @Mock private RecommendationEngine                                              engine;
    @Mock private VolatilityService                                                 volatilityService;
    @Mock private com.the3Cgrp.zupptrade.agent2.engine.math.BlackScholesCalculator blackScholes;

    private RecommendationService service;

    /** Short-strike for all PE short tests. T3 must be ≥ 23700. */
    private static final int PE_SHORT_STRIKE = 23700;
    /** Short strike for CE short tests. T3 must be ≤ 23800. */
    private static final int CE_SHORT_STRIKE = 23800;

    @BeforeEach
    void setUp() {
        service = new RecommendationService(
                signalRepository, userProfileRepository, tradeRepository,
                referenceDataRepository, optionChainClient, marketDataClient,
                engine, volatilityService, blackScholes, jsonUtil, ledger);
    }

    // ── Null override — no-op ─────────────────────────────────────────────────

    @Test
    void confirm_nullOverrideThresholds_applyThresholdOverrideNotCalled() {
        UUID tradeId = UUID.randomUUID();
        TradeEntity trade = buildPeShortTrade();
        when(tradeRepository.findById(tradeId)).thenReturn(Optional.of(trade));
        stubForTradeCardDtoFromEntity(List.of(peShortLeg(), peLongLeg()));
        when(tradeRepository.save(any())).thenAnswer(i -> i.getArgument(0));

        service.confirm(new TradeConfirmRequestDto(tradeId, ConfirmAction.CONFIRM, null, null, null));

        // toJson for thresholds must NOT be called — existing value stays unchanged
        verify(jsonUtil, never()).toJson(any(MonitorThresholdsDto.class));
    }

    // ── Valid PE short override ───────────────────────────────────────────────

    @Test
    void confirm_validPeShortOverrideAllFields_thresholdsUpdated() {
        UUID tradeId = UUID.randomUUID();
        TradeEntity trade = buildPeShortTrade();
        when(tradeRepository.findById(tradeId)).thenReturn(Optional.of(trade));
        stubForApplyThresholdOverride(List.of(peShortLeg(), peLongLeg()), existingPeThresholds());
        stubForTradeCardDtoFromEntity(List.of(peShortLeg(), peLongLeg()));
        when(jsonUtil.toJson(any())).thenReturn("UPDATED_THRESHOLDS_JSON");
        when(tradeRepository.save(any())).thenAnswer(i -> i.getArgument(0));

        // T1=23900, T2=23800, T3=23700 (PE short: T1 > T2 > T3 ✓; T3 = short strike ✓)
        service.confirm(new TradeConfirmRequestDto(tradeId, ConfirmAction.CONFIRM, null,
                new TradeConfirmRequestDto.OverrideThresholds(23900, 23800, 23700), null));

        MonitorThresholdsDto saved = captureWrittenThresholds();
        assertThat(saved.t1WatchNiftyLevel()).isEqualByComparingTo(BigDecimal.valueOf(23900));
        assertThat(saved.t2ReadjustNiftyLevel()).isEqualByComparingTo(BigDecimal.valueOf(23800));
        assertThat(saved.t3ExitNiftyLevel()).isEqualByComparingTo(BigDecimal.valueOf(23700));
        // Loss thresholds preserved from existing
        assertThat(saved.t2LossThreshold()).isEqualByComparingTo(new BigDecimal("50000"));
        assertThat(saved.t3LossThreshold()).isEqualByComparingTo(new BigDecimal("100000"));
    }

    @Test
    void confirm_partialPeShortOverride_onlyT1Updated_existingT2T3Kept() {
        UUID tradeId = UUID.randomUUID();
        TradeEntity trade = buildPeShortTrade();
        when(tradeRepository.findById(tradeId)).thenReturn(Optional.of(trade));
        // Existing: T1=23800, T2=23750, T3=23700
        stubForApplyThresholdOverride(List.of(peShortLeg(), peLongLeg()), existingPeThresholds());
        stubForTradeCardDtoFromEntity(List.of(peShortLeg(), peLongLeg()));
        when(jsonUtil.toJson(any())).thenReturn("UPDATED_THRESHOLDS_JSON");
        when(tradeRepository.save(any())).thenAnswer(i -> i.getArgument(0));

        // Override only T1 (must be > existing T2=23750)
        service.confirm(new TradeConfirmRequestDto(tradeId, ConfirmAction.CONFIRM, null,
                new TradeConfirmRequestDto.OverrideThresholds(23900, null, null), null));

        MonitorThresholdsDto saved = captureWrittenThresholds();
        assertThat(saved.t1WatchNiftyLevel()).isEqualByComparingTo(BigDecimal.valueOf(23900));
        // T2 and T3 kept from existing
        assertThat(saved.t2ReadjustNiftyLevel()).isEqualByComparingTo(new BigDecimal("23750"));
        assertThat(saved.t3ExitNiftyLevel()).isEqualByComparingTo(new BigDecimal("23700"));
    }

    // ── Valid CE short override ───────────────────────────────────────────────

    @Test
    void confirm_validCeShortOverrideAllFields_thresholdsUpdated() {
        UUID tradeId = UUID.randomUUID();
        TradeEntity trade = buildCeShortTrade();
        when(tradeRepository.findById(tradeId)).thenReturn(Optional.of(trade));
        stubForApplyThresholdOverride(List.of(ceShortLeg(), ceLongLeg()), existingCeThresholds());
        stubForTradeCardDtoFromEntity(List.of(ceShortLeg(), ceLongLeg()));
        when(jsonUtil.toJson(any())).thenReturn("UPDATED_THRESHOLDS_JSON");
        when(tradeRepository.save(any())).thenAnswer(i -> i.getArgument(0));

        // T1=23700, T2=23750, T3=23800 (CE short: T1 < T2 < T3 ✓; T3 = short strike ✓)
        service.confirm(new TradeConfirmRequestDto(tradeId, ConfirmAction.CONFIRM, null,
                new TradeConfirmRequestDto.OverrideThresholds(23700, 23750, 23800), null));

        MonitorThresholdsDto saved = captureWrittenThresholds();
        assertThat(saved.t1WatchNiftyLevel()).isEqualByComparingTo(BigDecimal.valueOf(23700));
        assertThat(saved.t2ReadjustNiftyLevel()).isEqualByComparingTo(BigDecimal.valueOf(23750));
        assertThat(saved.t3ExitNiftyLevel()).isEqualByComparingTo(BigDecimal.valueOf(23800));
    }

    // ── T3 PoP guard — PE short ───────────────────────────────────────────────

    @Test
    void confirm_t3BelowPeShortStrike_throwsIllegalArgument() {
        UUID tradeId = UUID.randomUUID();
        TradeEntity trade = buildPeShortTrade();
        when(tradeRepository.findById(tradeId)).thenReturn(Optional.of(trade));
        stubForApplyThresholdOverride(List.of(peShortLeg(), peLongLeg()), existingPeThresholds());

        // T3 = 23600 < PE_SHORT_STRIKE 23700 → PoP would drop below 50%
        assertThatThrownBy(() -> service.confirm(new TradeConfirmRequestDto(
                tradeId, ConfirmAction.CONFIRM, null,
                new TradeConfirmRequestDto.OverrideThresholds(null, null, 23600), null)))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("23600")
                .hasMessageContaining(String.valueOf(PE_SHORT_STRIKE));

        verify(tradeRepository, never()).save(any());
    }

    @Test
    void confirm_t3EqualToPeShortStrike_validBoundary_noException() {
        UUID tradeId = UUID.randomUUID();
        TradeEntity trade = buildPeShortTrade();
        when(tradeRepository.findById(tradeId)).thenReturn(Optional.of(trade));
        // T3 exactly at the short strike — PoP ≈ 50% at boundary, allowed
        stubForApplyThresholdOverride(List.of(peShortLeg(), peLongLeg()), existingPeThresholds());
        stubForTradeCardDtoFromEntity(List.of(peShortLeg(), peLongLeg()));
        when(jsonUtil.toJson(any())).thenReturn("UPDATED_JSON");
        when(tradeRepository.save(any())).thenAnswer(i -> i.getArgument(0));

        // T3 = PE_SHORT_STRIKE (23700), T2 = 23750, T1 = 23850 (ordering: 23850 > 23750 > 23700 ✓)
        assertThatNoException().isThrownBy(() -> service.confirm(new TradeConfirmRequestDto(
                tradeId, ConfirmAction.CONFIRM, null,
                new TradeConfirmRequestDto.OverrideThresholds(23850, 23750, PE_SHORT_STRIKE), null)));
    }

    // ── T3 PoP guard — CE short ───────────────────────────────────────────────

    @Test
    void confirm_t3AboveCeShortStrike_throwsIllegalArgument() {
        UUID tradeId = UUID.randomUUID();
        TradeEntity trade = buildCeShortTrade();
        when(tradeRepository.findById(tradeId)).thenReturn(Optional.of(trade));
        stubForApplyThresholdOverride(List.of(ceShortLeg(), ceLongLeg()), existingCeThresholds());

        // T3 = 23900 > CE_SHORT_STRIKE 23800 → PoP would drop below 50%
        assertThatThrownBy(() -> service.confirm(new TradeConfirmRequestDto(
                tradeId, ConfirmAction.CONFIRM, null,
                new TradeConfirmRequestDto.OverrideThresholds(null, null, 23900), null)))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("23900")
                .hasMessageContaining(String.valueOf(CE_SHORT_STRIKE));

        verify(tradeRepository, never()).save(any());
    }

    // ── Ordering violations — PE short ────────────────────────────────────────

    @Test
    void confirm_peShortT1LessThanT2_throwsIllegalArgument() {
        UUID tradeId = UUID.randomUUID();
        TradeEntity trade = buildPeShortTrade();
        when(tradeRepository.findById(tradeId)).thenReturn(Optional.of(trade));
        stubForApplyThresholdOverride(List.of(peShortLeg(), peLongLeg()), existingPeThresholds());

        // T1=23700 ≤ T2=23800 → violates T1 > T2 > T3 rule for PE short
        assertThatThrownBy(() -> service.confirm(new TradeConfirmRequestDto(
                tradeId, ConfirmAction.CONFIRM, null,
                new TradeConfirmRequestDto.OverrideThresholds(23700, 23800, 23700), null)))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("T1 watch level");

        verify(tradeRepository, never()).save(any());
    }

    @Test
    void confirm_peShortT2EqualT3_throwsIllegalArgument() {
        UUID tradeId = UUID.randomUUID();
        TradeEntity trade = buildPeShortTrade();
        when(tradeRepository.findById(tradeId)).thenReturn(Optional.of(trade));
        stubForApplyThresholdOverride(List.of(peShortLeg(), peLongLeg()), existingPeThresholds());

        // T2 = T3 (23700 = 23700) → violates T2 > T3 rule
        assertThatThrownBy(() -> service.confirm(new TradeConfirmRequestDto(
                tradeId, ConfirmAction.CONFIRM, null,
                new TradeConfirmRequestDto.OverrideThresholds(23850, 23700, 23700), null)))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("T2 readjust level");

        verify(tradeRepository, never()).save(any());
    }

    // ── Ordering violations — CE short ────────────────────────────────────────

    @Test
    void confirm_ceShortT1GreaterThanT2_throwsIllegalArgument() {
        UUID tradeId = UUID.randomUUID();
        TradeEntity trade = buildCeShortTrade();
        when(tradeRepository.findById(tradeId)).thenReturn(Optional.of(trade));
        stubForApplyThresholdOverride(List.of(ceShortLeg(), ceLongLeg()), existingCeThresholds());

        // T1=23800 ≥ T2=23750 → violates T1 < T2 < T3 rule for CE short
        assertThatThrownBy(() -> service.confirm(new TradeConfirmRequestDto(
                tradeId, ConfirmAction.CONFIRM, null,
                new TradeConfirmRequestDto.OverrideThresholds(23800, 23750, 23800), null)))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("T1 watch level");

        verify(tradeRepository, never()).save(any());
    }

    // ── Iron Condor — silently ignored ────────────────────────────────────────

    @Test
    void confirm_ironCondorOverride_silentlyIgnoredThresholdsUnchanged() {
        UUID tradeId = UUID.randomUUID();
        TradeEntity trade = buildIronCondorTrade();
        when(tradeRepository.findById(tradeId)).thenReturn(Optional.of(trade));
        // For IC, applyThresholdOverride returns immediately — no fromJson/toJson for threshold
        stubForTradeCardDtoFromEntity(List.of(peShortLeg(), peLongLeg(), ceShortLeg(), ceLongLeg()));
        when(tradeRepository.save(any())).thenAnswer(i -> i.getArgument(0));

        // Provide an override — should be silently ignored
        service.confirm(new TradeConfirmRequestDto(tradeId, ConfirmAction.CONFIRM, null,
                new TradeConfirmRequestDto.OverrideThresholds(23000, 22900, 22800), null));

        // No threshold JSON update should have been written
        verify(jsonUtil, never()).toJson(any(MonitorThresholdsDto.class));
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /**
     * Stubs the two fromJson calls inside applyThresholdOverride:
     *  1. fromJson(trade.getThresholds(), MonitorThresholdsDto.class) → existing thresholds
     *  2. fromJson(trade.getLegs(), TypeReference) → legs list
     */
    @SuppressWarnings("unchecked")
    private void stubForApplyThresholdOverride(List<TradeLegDto> legs,
                                                MonitorThresholdsDto existing) {
        when(jsonUtil.fromJson(anyString(), any(TypeReference.class))).thenReturn(legs);
        when(jsonUtil.fromJson(anyString(), eq(MonitorThresholdsDto.class))).thenReturn(existing);
    }

    /**
     * Stubs the three fromJson calls inside toTradeCardDtoFromEntity:
     *  summary, legs (TypeRef), gates (TypeRef), and thresholds (MonitorThresholdsDto).
     *
     * Uses doAnswer to distinguish legs calls (return legsList) from gates calls
     * (return empty list) by checking the GATES_JSON sentinel value in the string.
     */
    @SuppressWarnings("unchecked")
    private void stubForTradeCardDtoFromEntity(List<TradeLegDto> legs) {
        // fromJson(TypeRef) is called for both legs and gates — distinguish by value
        doAnswer(invocation -> {
            String json = (String) invocation.getArgument(0);
            return "GATES_JSON".equals(json) ? List.of() : legs;
        }).when(jsonUtil).fromJson(anyString(), any(TypeReference.class));

        when(jsonUtil.fromJson(anyString(), eq(MonitorThresholdsDto.class)))
                .thenReturn(existingPeThresholds());
        when(jsonUtil.fromJson(anyString(), eq(TradeSummary.class)))
                .thenReturn(emptySummary());
    }

    /** Captures the MonitorThresholdsDto written by applyThresholdOverride via toJson. */
    private MonitorThresholdsDto captureWrittenThresholds() {
        ArgumentCaptor<Object> captor = ArgumentCaptor.forClass(Object.class);
        verify(jsonUtil, atLeastOnce()).toJson(captor.capture());
        return captor.getAllValues().stream()
                .filter(v -> v instanceof MonitorThresholdsDto)
                .map(v -> (MonitorThresholdsDto) v)
                .findFirst()
                .orElseThrow(() -> new AssertionError("No MonitorThresholdsDto was passed to toJson"));
    }

    private TradeEntity buildPeShortTrade() {
        TradeEntity trade = new TradeEntity();
        trade.setStatus(TradeStatus.PENDING_CONFIRM);
        trade.setValidUntil(LocalDateTime.now().plusHours(1));
        trade.setStrategy(Strategy.BULL_PUT_SPREAD);
        trade.setLegs("LEGS_JSON");
        trade.setThresholds("THRESHOLDS_JSON");
        trade.setSummary("SUMMARY_JSON");
        trade.setGateResults("GATES_JSON");
        trade.setGeneratedAt(LocalDateTime.now());
        trade.setTradeCode("T-20260626-0001");
        return trade;
    }

    private TradeEntity buildCeShortTrade() {
        TradeEntity trade = buildPeShortTrade();
        trade.setStrategy(Strategy.BEAR_CALL_SPREAD);
        return trade;
    }

    private TradeEntity buildIronCondorTrade() {
        TradeEntity trade = buildPeShortTrade();
        trade.setStrategy(Strategy.IRON_CONDOR);
        return trade;
    }

    private TradeLegDto peShortLeg() {
        return new TradeLegDto(OptionType.PE, PE_SHORT_STRIKE, new BigDecimal("60.00"),
                LegAction.SELL, new BigDecimal("-0.20"), new BigDecimal("0.15"),
                "NFO_OPT|NIFTY|2026-07-01|23700|PE");
    }

    private TradeLegDto peLongLeg() {
        return new TradeLegDto(OptionType.PE, PE_SHORT_STRIKE - 100, new BigDecimal("35.00"),
                LegAction.BUY, new BigDecimal("-0.12"), new BigDecimal("0.08"),
                "NFO_OPT|NIFTY|2026-07-01|23600|PE");
    }

    private TradeLegDto ceShortLeg() {
        return new TradeLegDto(OptionType.CE, CE_SHORT_STRIKE, new BigDecimal("60.00"),
                LegAction.SELL, new BigDecimal("0.20"), new BigDecimal("0.15"),
                "NFO_OPT|NIFTY|2026-07-01|23800|CE");
    }

    private TradeLegDto ceLongLeg() {
        return new TradeLegDto(OptionType.CE, CE_SHORT_STRIKE + 100, new BigDecimal("35.00"),
                LegAction.BUY, new BigDecimal("0.12"), new BigDecimal("0.08"),
                "NFO_OPT|NIFTY|2026-07-01|23900|CE");
    }

    /**
     * Default existing PE short thresholds: T1=23800, T2=23750, T3=23700 (descending ✓).
     * T3 equals the short strike — valid boundary.
     */
    private MonitorThresholdsDto existingPeThresholds() {
        return MonitorThresholdsDto.twoLeg(
                new BigDecimal("23800"), new BigDecimal("23750"), new BigDecimal("23700"),
                new BigDecimal("50000"), new BigDecimal("100000"));
    }

    /**
     * Default existing CE short thresholds: T1=23700, T2=23750, T3=23800 (ascending ✓).
     * T3 equals the short strike — valid boundary.
     */
    private MonitorThresholdsDto existingCeThresholds() {
        return MonitorThresholdsDto.twoLeg(
                new BigDecimal("23700"), new BigDecimal("23750"), new BigDecimal("23800"),
                new BigDecimal("50000"), new BigDecimal("100000"));
    }

    private TradeSummary emptySummary() {
        return new TradeSummary(
                BigDecimal.ZERO, 0, 65,
                BigDecimal.ZERO, BigDecimal.ZERO, BigDecimal.ZERO,
                BigDecimal.ZERO, BigDecimal.ZERO, BigDecimal.ZERO,
                BigDecimal.ZERO, BigDecimal.ZERO, BigDecimal.ZERO);
    }
}
