#!/usr/bin/env python3
"""
Generate a full option_chain.csv for a scenario from its spot_vix.csv + scenario.yaml expiry.

For each trading date it writes CE + PE rows across ATM ± 500 (step 50), pricing each leg with
Black-Scholes at a flat vol (= that day's VIX / 100). This gives Agent 2 a real chain to select
strikes from, and Agent 3 monitoring LTPs for whatever strikes get picked.

Usage:  python3 gen_chain.py scenarios/bull_put_5day
Re-run after editing spot_vix.csv (or tweak STRIKE_RANGE / vol below) to reshape the chain.
"""
import sys, math, re
from datetime import date, datetime

R = 0.065           # risk-free rate
STRIKE_RANGE = 500  # ATM ± this, step 50
OI_PEAK = 1_200_000 # ATM open interest; falls off with distance


def ncdf(x):
    return 0.5 * (1.0 + math.erf(x / math.sqrt(2.0)))


def black_scholes(S, K, sigma, t, is_call):
    """Returns (price, delta, buyer_pop). buyer_pop = P(option expires ITM)."""
    if sigma <= 0 or t <= 0:
        if is_call:
            return max(0.0, S - K), (1.0 if S > K else 0.0), (1.0 if S > K else 0.0)
        return max(0.0, K - S), (-1.0 if S < K else 0.0), (1.0 if S < K else 0.0)
    d1 = (math.log(S / K) + (R + 0.5 * sigma * sigma) * t) / (sigma * math.sqrt(t))
    d2 = d1 - sigma * math.sqrt(t)
    if is_call:
        price = S * ncdf(d1) - K * math.exp(-R * t) * ncdf(d2)
        return price, ncdf(d1), ncdf(d2)
    price = K * math.exp(-R * t) * ncdf(-d2) - S * ncdf(-d1)
    return price, ncdf(d1) - 1.0, ncdf(-d2)


def read_expiry(scenario_dir):
    for line in open(scenario_dir + "/scenario.yaml", encoding="utf-8"):
        m = re.match(r"\s*expiry:\s*(\S+)", line)
        if m:
            return date.fromisoformat(m.group(1))
    raise SystemExit("scenario.yaml: no 'expiry:' found")


def read_spot_vix(scenario_dir):
    """First spot/vix per date (representative daily value)."""
    per_date = {}
    for line in open(scenario_dir + "/spot_vix.csv", encoding="utf-8"):
        s = line.strip()
        if not s or s.startswith("#") or s.lower().startswith("time"):
            continue
        t, spot, vix = [x.strip() for x in s.split(",")[:3]]
        d = datetime.fromisoformat(t).date()
        if d not in per_date:
            per_date[d] = (float(spot), float(vix))
    return per_date


def main():
    scenario_dir = sys.argv[1] if len(sys.argv) > 1 else "."
    expiry = read_expiry(scenario_dir)
    per_date = read_spot_vix(scenario_dir)

    rows = []
    for d in sorted(per_date):
        spot, vix = per_date[d]
        sigma = vix / 100.0
        t = max((expiry - d).days, 0) / 365.0
        atm = int(round(spot / 50.0) * 50)
        for K in range(atm - STRIKE_RANGE, atm + STRIKE_RANGE + 1, 50):
            oi = int(OI_PEAK * math.exp(-((K - atm) / 300.0) ** 2))
            for is_call, typ in ((True, "CE"), (False, "PE")):
                price, delta, pop = black_scholes(spot, K, sigma, t, is_call)
                rows.append((d.isoformat(), K, typ, round(price, 2),
                             round(sigma, 4), round(delta, 3), oi, round(pop, 3)))

    out = scenario_dir + "/option_chain.csv"
    with open(out, "w", encoding="utf-8") as f:
        f.write("# GENERATED by gen_chain.py — full chain, flat vol = vix/100. "
                "Edit spot_vix.csv + rerun to reshape.\n")
        f.write("date,strike,type,ltp,iv,delta,oi,pop\n")
        for row in rows:
            f.write(",".join(str(x) for x in row) + "\n")
    print(f"wrote {len(rows)} rows to {out}")


if __name__ == "__main__":
    main()
